show the notification text as bubble when sent from webchat
Yeldaai/chat-plugin pull request #107
Opened 2021-12-06 17:33 UTC by vishnu-ravi

Trello card: https://trello.com/c/EHhgX0gI/1736-webchat-support-notification-appeareance-options

2021-12-06 17:46 UTC, meelie requested changes
Can you please add test to check the innerText is only displayed when bubbleText or notification text ? And properly remove only when needed in both cases ?
Thanks

2021-12-06 17:46 UTC, meelie commented on src/js/yeldaWebchatInjector.js
> +    if (!this.webChatContainer || ((!this.webchatSettings || !this.webchatSettings.bubbleText) && !text)) {
I would do 

```js
text = text || (webchatSettings && webchatSettings.bubbleText)
```

and then only check that text presence

2021-12-07 11:01 UTC, codebynao approved these changes
Thanks!

2021-12-07 11:12 UTC, merged

2021-12-09 15:40 UTC, meelie reviewed
2 additionnal feedback
Thanks !